version: '3.8'

services:
  client:
    image: bishal-agro-seed/client:latest  
    ports:
      - 5000:80
    environment:
      - TZ=Asia/Kathmandu
    networks:
      - bishal-agro-seed-portal
  server:
    image: bishal-agro-seed/server:latest 
    ports:
      - 5001:80
    configs:
      - source: bishal-agro-seed-server-appsettings.json
        target: /app/appsettings.json        
    environment:
      - TZ=Asia/Kathmandu
    networks:
      - bishal-agro-seed-portal
  
networks:
  bishal-agro-seed-portal:

configs:
   bishal-agro-seed-server-appsettings.json:
    external: true
