version: '3.8'

services:
  client:
    image: bishal-agro-seed/client:latest  
    ports:
      - 5000:80
    environment:
      - TZ=Asia/Kathmandu
    networks:
      - bishal-agro-seed-portal

networks:
  bishal-agro-seed-portal:
