version: '3.8'
services:
  database:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      TZ: 'Asia/Kathmandu'
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'yHMd.@3WQtxtcjE'
    ports:
      - 14333:1433
    volumes: 
      - sql_server_data:/var/opt/mssql
    networks:
      - bishal-agro-seed-portal

volumes:
  sql_server_data:

networks:
  bishal-agro-seed-portal: